version: '3.4'
services:
  db-vibe-bus:
    container_name: db-vibe-bus
    image: postgres:latest
    environment:
      POSTGRES_DB: VibeBus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qweASD!@#
    ports: 
      - "5448:5432" 
    networks:
      - vibe-bus-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api-vibe-bus:
    container_name: api-vibe-bus
    build: 
      context: ../
      dockerfile: ./VibeBusWeb.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db-vibe-bus
    ports:
      - "8096:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  vibe-bus-dev:
    driver: bridge
